# .github/workflows/docker-publish.yml
name: Build and Push Test Docker Image

on:
  push:
    branches: ["main"] # 当 main 分支有更新时触发

jobs:
  build_and_push_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Camoufox Download URL
        id: get_camoufox_url
        run: |
          URL=$(curl -s "https://api.github.com/repos/${{ github.repository }}/releases/latest" | grep "browser_download_url.*camoufox-linux.tar.gz" | cut -d : -f 2,3 | tr -d '", ')
          echo "CAMOUFOX_URL=$URL" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to Test Repository
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          # 关键！这里填写你的测试仓库地址
          tags: ellinalopez/cloud-studio:latest
          build-args: |
            CAMOUFOX_URL=${{ env.CAMOUFOX_URL }}
